name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake ninja-build g++ pkg-config \
            libgl1-mesa-dev libx11-dev libxrandr-dev \
            libxinerama-dev libxcursor-dev libxi-dev \
            wayland-protocols libwayland-dev

      - name: Configure
        run: cmake -S . -B build-ci -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build-ci --config Release